#!/usr/bin/env ruby
require File.expand_path(File.dirname(__FILE__) + "/daemon")

class ResqueDaemon
  include Gitoriousd::Daemon

  def initialize(name)
    @name = name
  end

  def run_resque
    pid = fork do
      exec "#{ENV['GITORIOUS_HOME']}/bin/rake resque:work QUEUE=*"
    end
    return pid
  end

  def run!
    daemonize_app do
      @resque_pid = run_resque
      write_to_log_file "Resque running with pid #{@resque_pid}, controlled by #{Process.pid}"
      Signal.trap(:QUIT) do
        Process.kill(:QUIT, @resque_pid)
        pid, status = Process.waitpid2(@resque_pid)
        write_to_log_file "Resque with PID #{@resque_pid} killed, status was #{status.exitstatus}"
        remove_pidfile
        exit status.exitstatus
      end
      Signal.trap(:HUP) {
        write_to_log_file "Restarting Resque with PID #{@resque_pid}"
        Process.kill(:QUIT, @resque_pid)
        Process.waitpid(@resque_pid)
        write_to_log_file "Old Resque worker dead, will re-spawn"
        @resque_pid = run_resque
        write_to_log_file "Resque respawned, running with pid #{@resque_pid}"
      }
      loop {
        sleep 1
      }
    end
  end
end

daemon = ResqueDaemon.new("resque")
daemon.run!
